// Functions 1 + 2 — GAR aggregation (onStaleGarCreated + garNightlyBackstop).
// Both SHIP DORMANT. Enable via Config/featureFlags.useCloudGAR = true.
//
// Gates in order:
//   1. useCloudGAR feature flag — global kill switch
//   2. Minimum cohort of 3 distinct users in the system (k-anonymity floor)
//
// Architecture:
//   - Marker IDs are autogenerated (addDoc semantics) — multiple flushes for
//     the same {system, date} produce N markers, all processed against the
//     same keyspace (Clyde CRITICAL #1).
//   - Claim-then-process via a single-doc Firestore transaction prevents
//     trigger+backstop double-write races (Clyde CRITICAL #2).
//   - Backstop runs marker processing FIRST, then reaffirms last 7 days; this
//     ordering prevents stale 7-day-old data from overwriting a fresh
//     trigger-driven result.
//   - Expired markers (>30 days) are silently deleted, not processed.

import { onDocumentCreated } from 'firebase-functions/v2/firestore';
import { onSchedule } from 'firebase-functions/v2/scheduler';
import { Timestamp } from 'firebase-admin/firestore';
import { readFlags } from './lib/featureFlags';
import {
  claimMarker,
  recomputeStats,
  deleteMarker,
  listMarkers,
  markerIsExpired,
  cohortSizeForSystem,
  MIN_COHORT,
} from './lib/groupStats';
import type { StaleMarker } from './lib/types';

const COMMON_OPTS = {
  region: 'us-central1' as const,
  memory: '512MiB' as const,
};

/** Process a single marker through the claim-then-process pipeline. Returns the resulting status. */
async function processMarker(marker: StaleMarker, claimerLabel: string): Promise<string> {
  if (markerIsExpired(marker)) {
    await deleteMarker(marker.id);
    return `expired-deleted:${marker.id}`;
  }
  const claimed = await claimMarker(marker.id, claimerLabel);
  if (!claimed) return `claim-lost:${marker.id}`;
  try {
    const result = await recomputeStats(claimed.system, claimed.date);
    if (result.written) {
      await deleteMarker(marker.id);
      return `processed:${claimed.system}/${claimed.date} cohort=${result.cohortSize}`;
    }
    // Cohort gate or no-sessions case — delete the marker; recomputing later
    // won't help unless cohort grows, which is fine: future markers will retry.
    await deleteMarker(marker.id);
    return `skipped:${claimed.system}/${claimed.date} reason=${result.reason}`;
  } catch (err) {
    console.error(`Marker ${marker.id} processing failed:`, err);
    // Leave the marker (claim will expire after 5 min, retryable by backstop)
    return `error:${marker.id}`;
  }
}

export const onStaleGarCreated = onDocumentCreated(
  {
    document: 'staleGAR/{markerId}',
    ...COMMON_OPTS,
  },
  async (event) => {
    const flags = await readFlags();
    if (!flags.useCloudGAR) return;

    const snap = event.data;
    if (!snap) return;
    const data = snap.data() as Omit<StaleMarker, 'id'>;
    const marker: StaleMarker = { id: event.params.markerId, ...data };

    // Cohort gate (cheap pre-check before claim transaction).
    const cohort = await cohortSizeForSystem(marker.system);
    if (cohort < MIN_COHORT) {
      console.log(`onStaleGarCreated: ${marker.system} cohort=${cohort} < ${MIN_COHORT}; deleting marker without compute`);
      await deleteMarker(marker.id);
      return;
    }

    const status = await processMarker(marker, `trigger:${event.params.markerId}`);
    console.log(`onStaleGarCreated: ${status}`);
  },
);

export const garNightlyBackstop = onSchedule(
  {
    schedule: '0 3 * * *',
    timeZone: 'America/Chicago',
    ...COMMON_OPTS,
    timeoutSeconds: 540,
  },
  async () => {
    const flags = await readFlags();
    if (!flags.useCloudGAR) {
      console.log('garNightlyBackstop: disabled by feature flag; exiting');
      return;
    }

    // Phase A — process any outstanding markers first.
    const allMarkers = await listMarkers();
    const claimerLabel = `backstop:${new Date().toISOString()}`;
    let processed = 0;
    let skipped = 0;
    let errored = 0;
    for (const m of allMarkers) {
      const status = await processMarker(m, claimerLabel);
      if (status.startsWith('processed')) processed++;
      else if (status.startsWith('error')) errored++;
      else skipped++;
    }
    console.log(`garNightlyBackstop A: markers=${allMarkers.length} processed=${processed} skipped=${skipped} errored=${errored}`);

    // Phase B — defense-in-depth: reaffirm last 7 days of GAR per system
    // with a known cohort.
    // Discover systems by listing distinct system field across the last 30
    // days of sessions. Cheaper than maintaining a separate registry.
    const { getFirestore } = await import('firebase-admin/firestore');
    const db = getFirestore();
    const since = Timestamp.fromMillis(Date.now() - 30 * 86400 * 1000);
    const recent = await db.collectionGroup('sessions')
      .where('startTime', '>=', since)
      .select('system')
      .limit(2000)
      .get();
    const systems = new Set<string>();
    for (const d of recent.docs) {
      const sys = (d.data() as { system?: string }).system;
      if (sys) systems.add(sys);
    }

    let reaffirmed = 0;
    let skippedByCohort = 0;
    for (const sys of systems) {
      const cohort = await cohortSizeForSystem(sys);
      if (cohort < MIN_COHORT) { skippedByCohort++; continue; }
      for (let daysBack = 1; daysBack <= 7; daysBack++) {
        const d = new Date(Date.now() - daysBack * 86400 * 1000);
        const dateStr = d.toISOString().slice(0, 10);
        try {
          const r = await recomputeStats(sys, dateStr);
          if (r.written) reaffirmed++;
        } catch (err) {
          console.warn(`Reaffirm ${sys}/${dateStr} failed:`, err);
        }
      }
    }
    console.log(`garNightlyBackstop B: systems=${systems.size} reaffirmed=${reaffirmed} skippedByCohort=${skippedByCohort}`);
  },
);
